name: Production Deployemnt
on:
    push:
        branches: [production]

jobs:
    deploy:
        runs-on: [self-hosted, linux, x64]
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  -version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build
            node- run: pm2 restart select-safaris-landing
